# Generated by Django 4.2 on 2023-09-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='narxi',
            new_name='hozirgi_narx',
        ),
        migrations.AddField(
            model_name='post',
            name='oldingi_narx',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tavsif',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
