# Generated by Django 4.2 on 2023-09-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_narxi_post_hozirgi_narx_post_oldingi_narx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sotuvda_nechta',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
