# Generated by Django 4.2 on 2023-09-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_post_sotuvda_nechta'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='asosis_kamera',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='barcha_malumotlar',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='batareya_quvvati',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='brand_nomi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ekran_dioganali',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='old_kamera',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='operativ_xotira',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='operatsion_tizim',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='protsessor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='xotira',
            field=models.IntegerField(null=True),
        ),
    ]
