# Generated by Django 4.2 on 2023-09-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_post_asosis_kamera_post_barcha_malumotlar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ekran_dioganali',
            field=models.FloatField(null=True),
        ),
    ]
